# Generated by Django 5.0.4 on 2026-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='request_qrs/'),
        ),
    ]
