# Generated by Django 5.0.4 on 2026-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookissue_return_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
