# Generated by Django 5.0.4 on 2026-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookissue_qr_token_bookrequest_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='return_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='return_qrs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='request_qrs/%Y/%m/%d/'),
        ),
    ]
