# Generated by Django 5.0.4 on 2026-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_category_options_alter_book_available_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Muallif'),
        ),
    ]
