# Generated by Django 5.0.4 on 2026-04-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_address'),
        ('schools', '0004_alter_district_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('school_admin', 'School Admin'), ('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Maktab'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan'),
        ),
    ]
