# Generated by Django 5.0.4 on 2026-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_address_alter_customuser_birth_date_and_more'),
        ('accounts', '0005_customuser_raw_password_alter_customuser_id'),
    ]

    operations = [
    ]
