# Generated by Django 5.0.4 on 2026-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260428_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ochiq parol'),
        ),
    ]
