# Generated by Django 5.0.4 on 2026-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
