# Generated by Django 5.0.4 on 2026-04-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_school', '0002_news_image'),
        ('schools', '0004_alter_district_name_alter_institution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
