# Generated by Django 5.0.4 on 2026-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_school', '0003_alter_news_options_alter_news_body_and_more'),
        ('frontend_school', '0003_alter_news_school'),
    ]

    operations = [
    ]
