# Generated by Django 5.0.4 on 2026-04-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_school', '0004_merge_20260428_1838'),
        ('schools', '0006_alter_district_name_alter_institution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Maktab'),
        ),
    ]
