# Generated by Django 5.0.4 on 2026-04-28 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Muassasa', 'verbose_name_plural': 'Muassasalar'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Maktab', 'verbose_name_plural': 'Maktablar'},
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tuman nomi'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Muassasa nomi'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Maktab nomi'),
        ),
    ]
