# Generated by Django 5.0.4 on 2026-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_district_name_alter_institution_name_and_more'),
        ('schools', '0004_alter_district_options_alter_institution_options_and_more'),
    ]

    operations = [
    ]
