# Generated by Django 5.0.4 on 2026-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookrequest_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='return_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='return_qrs/'),
        ),
    ]
